apiVersion: v1
kind: Template
metadata:
  name: developer-crud-app-template
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: developer-crud-app-config
  data:
    QUARKUS_DATASOURCE_URL: ${DATABASE_URL}
    DEPLOYMENT_ENVIRONMENT: kubernetes
    SERVICE_NAME: developer-crud-app-kubernetes
- apiVersion: v1
  kind: Secret
  type: Opaque
  metadata:
    annotations:
      template.openshift.io/base64-expose-password: '{.data[''database-password'']}'
      template.openshift.io/expose-username: '{.data[''database-user'']}'
    name: developer-crud-app-secret
  stringData: 
    QUARKUS_DATASOURCE_USERNAME: ${DATABASE_USER}
    QUARKUS_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: developer-crud-app
    name: developer-crud-app
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: developer-crud-app
    template:
      metadata:
        labels:
          app: developer-crud-app
      spec:
        containers:
        - image: ${CONTAINER_IMAGE}
          imagePullPolicy: Always
          name: developer-crud-app
          envFrom:
          - configMapRef:
              name: developer-crud-app-config
          - secretRef:
              name: developer-crud-app-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 9999
            initialDelaySeconds: 1
            periodSeconds: 5
          terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: developer-crud-app
    name: developer-crud-app
  spec:
    ports:    
    - port: 9999
      protocol: TCP
      targetPort: 9999
      name: http
    selector:
      app: developer-crud-app
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: developer-crud-app
    name: developer-crud-app
  spec:
    to:
      kind: Service
      name: developer-crud-app
      weight: 100
parameters:
- description: Password used for connect to the database
  displayName: DB Connection password
  required: true
  name: DATABASE_PASSWORD
  value: test
- description: Username used for connect to the database
  displayName: DB Connection username
  required: true
  name: DATABASE_USER
  value: test
- description: DB Connection URL
  displayName: DB Connection URL
  name: DATABASE_URL
  value: jdbc:postgresql://developer-database:5432/developer
- description: Container image name, including registry url
  displayName: Container image name, including registry url
  required: true
  name: CONTAINER_IMAGE
  value: quay.io/famargon/developer-crud-app
labels:
  template: developer-crud-app-template