apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: developer-crud-app
    name: developer-crud-app
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: developer-crud-app
    template:
      metadata:
        labels:
          app: developer-crud-app
      spec:
        containers:
        - image: quay.io/famargon/developer-crud-app
          imagePullPolicy: Always
          name: developer-crud-app
          envFrom:
          - configMapRef:
              name: developer-crud-app-config
          # env:
          #   - name: QUARKUS_DATASOURCE_URL
          #     value: jdbc:postgresql://postgresql-95-centos7.quarkus-msvcs.svc:5432/developer-db
          #   - name: QUARKUS_DATASOURCE_USERNAME
          #     value: quarkus-user
          #   - name: QUARKUS_DATASOURCE_PASSWORD
          #     value: quarkus-pwd
          #   - name:  DEPLOYMENT_ENVIRONMENT
          #     value: kubernetes
          #   - name:  SERVICE_NAME
          #     value: developer-crud-app-kubernetes
          livenessProbe:
            httpGet:
              path: /health
              port: 9999
            initialDelaySeconds: 1
            periodSeconds: 5
          terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: developer-crud-app
    name: developer-crud-app
  spec:
    ports:    
    - port: 9999
      protocol: TCP
      targetPort: 9999
      name: http
    selector:
      app: developer-crud-app
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: developer-crud-app
    name: developer-crud-app
  spec:
    to:
      kind: Service
      name: developer-crud-app
      weight: 100
